language: node_js
node_js:
- '4.4.3'
env:
  matrix:
  - CXX=g++-4.8
cache:
  directories:
  - node_modules
before_script:
- webpack
notifications:
  email:
    on_success: never
    on_failure: always
